/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package meuprojeto;

import java.util.ArrayList;
import java.util.Collections;
import javax.swing.JOptionPane;
import meuprojeto.entity.Bairro;

/**
 *
 * @author farah
 */
public class CadastroDeBairros extends javax.swing.JInternalFrame {

    private ArrayList<Bairro> listaBairros;
    
    private static CadastroDeBairros INSTANCIA;

    public CadastroDeBairros() {
        this.listaBairros = new ArrayList<Bairro>();
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtNome = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        getContentPane().setLayout(new java.awt.FlowLayout());

        jLabel1.setText("Nome");
        getContentPane().add(jLabel1);

        txtNome.setText("jTextField1");
        txtNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNomeActionPerformed(evt);
            }
        });
        getContentPane().add(txtNome);

        jButton1.setText("Adicionar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String nomeBairro = txtNome.getText();
      if(nomeBairro.equals("")){
          JOptionPane.showMessageDialog(this,"O Campo Nome é obrigatório!");
      
      }else{
        int id = listaBairros.size();
        Bairro bairro = new Bairro();
        bairro.setId(id);
        bairro.setNome(nomeBairro);
        listaBairros.add(bairro);
        //Collections.sort(listaBairros);
        //tabelaClientes = new MeuTableModel(listaClientes);
        //tblClientes.setModel(tabelaClientes);
          //Modelo da Tabela
        //DefaultTableModel tabelaClientes = (DefaultTableModel) tblClientes.getModel();
        //DefaultTableModel tabelaClientes = new DefaultTableModel());
        //tabelaClientes.addRow(new Object[]{nomeCliente});
        txtNome.setText("");
      }
      txtNome.requestFocus();
    }//GEN-LAST:event_jButton1ActionPerformed

    public ArrayList<Bairro> getListaBairros() {
        return listaBairros;
    }

    public void setListaBairros(ArrayList<Bairro> listaBairros) {
        this.listaBairros = listaBairros;
    }

    private void txtNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNomeActionPerformed

    public static CadastroDeBairros getInstance(){
        if(INSTANCIA == null)
            INSTANCIA = new CadastroDeBairros();
        return INSTANCIA;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField txtNome;
    // End of variables declaration//GEN-END:variables
}
