/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package meuprojeto;

import java.util.ArrayList;
import java.util.List;
import javax.swing.table.AbstractTableModel;
import meuprojeto.dao.PaisDAO;
import meuprojeto.entity.Pais;

/**
 *
 * @author farah
 */
public class CadastroDePaises extends javax.swing.JInternalFrame {

    private List<Pais> listaPaises;
    
    private static CadastroDePaises INSTANCIA;
    
    /**
     * Creates new form CadastroPais
     */
    public CadastroDePaises() {
        
        initComponents();
        try{
            TableModelPaises tmp = new TableModelPaises();
            tblPais.setModel(tmp);
        }catch(Exception e){
            e.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtNome = new javax.swing.JTextField();
        btnSalvar = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblPais = new javax.swing.JTable();

        jLabel1.setText("Nome:");
        jPanel1.add(jLabel1);

        txtNome.setMinimumSize(new java.awt.Dimension(150, 33));
        txtNome.setPreferredSize(new java.awt.Dimension(150, 33));
        txtNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNomeActionPerformed(evt);
            }
        });
        jPanel1.add(txtNome);

        btnSalvar.setText("Salvar");
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });
        jPanel1.add(btnSalvar);

        getContentPane().add(jPanel1, java.awt.BorderLayout.NORTH);

        tblPais.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tblPais);

        jPanel2.add(jScrollPane1);

        getContentPane().add(jPanel2, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNomeActionPerformed

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
        Pais p = new Pais();
        p.setNome(txtNome.getText());
        PaisDAO.salvar(p);
        TableModelPaises tmp = new TableModelPaises();
        tblPais.setModel(tmp);
    }//GEN-LAST:event_btnSalvarActionPerformed

    class TableModelPaises extends AbstractTableModel {
        private String[] nomeColunas = {"Código", "Nome"};
        //private Object[][] dados = new Object[10][10];
        private List<Pais> listaPaises;

        public TableModelPaises(){
            this.listaPaises = (List<Pais>) PaisDAO.listar();            
            this.setColumnName(0,"Código");
            this.setColumnName(1,"Nome");
        }
        
        @Override
        public String getColumnName(int i) {
            return nomeColunas[i];
        }
            
        
        public void setColumnName(int i, String name) {
            nomeColunas[i] = name;
        }

        @Override
        public int getRowCount() {
            return listaPaises.size();
        }

        @Override
        public int getColumnCount() {
            return nomeColunas.length;
        }

        @Override
        public Object getValueAt(int l, int c) {
            Pais p = (Pais)listaPaises.get(l);
            Object valor = null;
            switch(c){
                case 0: valor = p.getId();
                        break;
                case 1: valor = p.getNome();
            }
            return valor;
        }

    }

    public static CadastroDePaises getInstance(){
        if(INSTANCIA == null)
            INSTANCIA = new CadastroDePaises();
        return INSTANCIA;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSalvar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblPais;
    private javax.swing.JTextField txtNome;
    // End of variables declaration//GEN-END:variables
}
