/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package meuprojeto;

import java.awt.List;
import java.util.ArrayList;
import java.util.Collections;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.table.AbstractTableModel;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import meuprojeto.entity.Bairro;
import meuprojeto.entity.Cliente;

/**
 *
 * @author farah
 */
public class CadastroDeClientes extends javax.swing.JInternalFrame {
    private static CadastroDeClientes INSTANCIA;
    
    private ArrayList<Cliente> listaClientes;
    private ArrayList<Bairro> listaBairros;
    private TableModel tabelaClientes;
    private int tamanho;
    
    private CadastroDeClientes() {
        this.listaClientes = new ArrayList<Cliente>();
        
        initComponents();  
        
    }
    
    public static CadastroDeClientes getInstance(){
        if(INSTANCIA == null)
            INSTANCIA = new CadastroDeClientes();
        return INSTANCIA;
    }
    
    
    class MeuTableModel extends AbstractTableModel {
        private String[] nomeColunas = {"Código", "Nome"};
        //private Object[][] dados = new Object[10][10];
        private ArrayList<Cliente> listaClientes;

        public MeuTableModel(ArrayList<Cliente> lista){
            System.out.println("meutablemodel...");
            this.listaClientes = new ArrayList<>(lista);
            this.setColumnName(0,"Código");
            this.setColumnName(1,"Nome");
        }
        
        @Override
        public String getColumnName(int i) {
            return nomeColunas[i];
        }
            
        
        public void setColumnName(int i, String name) {
            nomeColunas[i] = name;
        }

        @Override
        public int getRowCount() {
            return listaClientes.size();
        }

        @Override
        public int getColumnCount() {
            return nomeColunas.length;
        }

        @Override
        public Object getValueAt(int l, int c) {
            Cliente cli = listaClientes.get(l);
            Object valor = null;
            switch(c){
                case 0: valor = cli.getId();
                        break;
                case 1: valor = cli.getNome();
            }
            return valor;
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtNome = new javax.swing.JTextField();
        cbbBairros = new javax.swing.JComboBox();
        btnAdicionarNome = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblClientes = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Clientes");
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameClosed(evt);
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
        });

        jLabel1.setFont(new java.awt.Font("Cantarell", 1, 15)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(85, 142, 249));
        jLabel1.setText("Nome:");
        jPanel1.add(jLabel1);

        txtNome.setMinimumSize(new java.awt.Dimension(150, 33));
        txtNome.setPreferredSize(new java.awt.Dimension(150, 33));
        jPanel1.add(txtNome);

        cbbBairros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbbBairrosActionPerformed(evt);
            }
        });
        cbbBairros.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                cbbBairrosFocusGained(evt);
            }
        });
        jPanel1.add(cbbBairros);

        btnAdicionarNome.setFont(new java.awt.Font("Cantarell", 1, 15)); // NOI18N
        btnAdicionarNome.setForeground(new java.awt.Color(11, 160, 17));
        btnAdicionarNome.setMnemonic('A');
        btnAdicionarNome.setText("Adicionar");
        btnAdicionarNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdicionarNomeActionPerformed(evt);
            }
        });
        jPanel1.add(btnAdicionarNome);

        getContentPane().add(jPanel1, java.awt.BorderLayout.NORTH);

        tblClientes.setModel(new MeuTableModel(new ArrayList<Cliente>()));
        jScrollPane1.setViewportView(tblClientes);

        jPanel2.add(jScrollPane1);

        getContentPane().add(jPanel2, java.awt.BorderLayout.CENTER);

        jButton1.setFont(new java.awt.Font("Cantarell", 1, 15)); // NOI18N
        jButton1.setForeground(new java.awt.Color(249, 16, 13));
        jButton1.setMnemonic('R');
        jButton1.setText("Remover");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton1);

        getContentPane().add(jPanel3, java.awt.BorderLayout.SOUTH);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAdicionarNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdicionarNomeActionPerformed
      String nomeCliente = txtNome.getText();
      if(nomeCliente.equals("")){
          JOptionPane.showMessageDialog(this,"O Campo Nome é obrigatório!");
      
      }else{
        int id = listaClientes.size();
        Cliente cliente = new Cliente();
        cliente.setId(id);
        cliente.setNome(nomeCliente);
        cliente.setBairro((Bairro)cbbBairros.getSelectedItem());
        listaClientes.add(cliente);
        Collections.sort(listaClientes);
        tabelaClientes = new MeuTableModel(listaClientes);
        tblClientes.setModel(tabelaClientes);
          //Modelo da Tabela
        //DefaultTableModel tabelaClientes = (DefaultTableModel) tblClientes.getModel();
        //DefaultTableModel tabelaClientes = new DefaultTableModel());
        //tabelaClientes.addRow(new Object[]{nomeCliente});
        txtNome.setText("");
      }
      txtNome.requestFocus();
    }//GEN-LAST:event_btnAdicionarNomeActionPerformed

    
    
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        //((DefaultTableModel)tblClientes.getModel()).removeRow(tblClientes.getSelectedRow());
        JOptionPane.showMessageDialog(this, tblClientes.getValueAt(tblClientes.getSelectedRow(), 0));
        System.out.println("Não implementado ainda...");
    }//GEN-LAST:event_jButton1ActionPerformed

    private void formInternalFrameClosed(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameClosed
        
    }//GEN-LAST:event_formInternalFrameClosed

    private void cbbBairrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbbBairrosActionPerformed
        
                
        
    }//GEN-LAST:event_cbbBairrosActionPerformed

    private void cbbBairrosFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cbbBairrosFocusGained
        listaBairros = CadastroDeBairros.getInstance().getListaBairros();
        
        cbbBairros.removeAllItems();
        for(Bairro bairro:listaBairros){
            cbbBairros.addItem(bairro);
        }
    }//GEN-LAST:event_cbbBairrosFocusGained


    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdicionarNome;
    private javax.swing.JComboBox cbbBairros;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblClientes;
    private javax.swing.JTextField txtNome;
    // End of variables declaration//GEN-END:variables
}

